// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleUserMsg.proto

#ifndef PROTOBUF_BattleUserMsg_2eproto__INCLUDED
#define PROTOBUF_BattleUserMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace BattleMsg {
class BattleSingleFrame_S2C;
class BattleSingleFrame_S2CDefaultTypeInternal;
extern BattleSingleFrame_S2CDefaultTypeInternal _BattleSingleFrame_S2C_default_instance_;
class BattleUserBroadcast;
class BattleUserBroadcastDefaultTypeInternal;
extern BattleUserBroadcastDefaultTypeInternal _BattleUserBroadcast_default_instance_;
class BattleUserGameStart_S2C;
class BattleUserGameStart_S2CDefaultTypeInternal;
extern BattleUserGameStart_S2CDefaultTypeInternal _BattleUserGameStart_S2C_default_instance_;
class BattleUserLoadOK_C2S;
class BattleUserLoadOK_C2SDefaultTypeInternal;
extern BattleUserLoadOK_C2SDefaultTypeInternal _BattleUserLoadOK_C2S_default_instance_;
class BattleUserLoadOK_S2C;
class BattleUserLoadOK_S2CDefaultTypeInternal;
extern BattleUserLoadOK_S2CDefaultTypeInternal _BattleUserLoadOK_S2C_default_instance_;
class BattleUserLogin_C2S;
class BattleUserLogin_C2SDefaultTypeInternal;
extern BattleUserLogin_C2SDefaultTypeInternal _BattleUserLogin_C2S_default_instance_;
class BattleUserLogin_S2C;
class BattleUserLogin_S2CDefaultTypeInternal;
extern BattleUserLogin_S2CDefaultTypeInternal _BattleUserLogin_S2C_default_instance_;
class BattleUserLogout;
class BattleUserLogoutDefaultTypeInternal;
extern BattleUserLogoutDefaultTypeInternal _BattleUserLogout_default_instance_;
class BattleUserOperate_C2S;
class BattleUserOperate_C2SDefaultTypeInternal;
extern BattleUserOperate_C2SDefaultTypeInternal _BattleUserOperate_C2S_default_instance_;
}  // namespace BattleMsg

namespace BattleMsg {

namespace protobuf_BattleUserMsg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_BattleUserMsg_2eproto

enum EnumBattleUserMsg {
  eBattleMsg_Unknown = 0,
  eBattleMsg_Login = 1,
  eBattleMsg_LoadOK = 2,
  eBattleMsg_GameStart = 3,
  eBattleMsg_UserOperate = 4,
  eBattleMsg_SingleFrame = 5,
  eBattleMsg_Logout = 6,
  EnumBattleUserMsg_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EnumBattleUserMsg_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EnumBattleUserMsg_IsValid(int value);
const EnumBattleUserMsg EnumBattleUserMsg_MIN = eBattleMsg_Unknown;
const EnumBattleUserMsg EnumBattleUserMsg_MAX = eBattleMsg_Logout;
const int EnumBattleUserMsg_ARRAYSIZE = EnumBattleUserMsg_MAX + 1;

const ::google::protobuf::EnumDescriptor* EnumBattleUserMsg_descriptor();
inline const ::std::string& EnumBattleUserMsg_Name(EnumBattleUserMsg value) {
  return ::google::protobuf::internal::NameOfEnum(
    EnumBattleUserMsg_descriptor(), value);
}
inline bool EnumBattleUserMsg_Parse(
    const ::std::string& name, EnumBattleUserMsg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumBattleUserMsg>(
    EnumBattleUserMsg_descriptor(), name, value);
}
enum BattleErrCode {
  eBEC_Success = 0,
  eBEC_Fail = 1,
  BattleErrCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BattleErrCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BattleErrCode_IsValid(int value);
const BattleErrCode BattleErrCode_MIN = eBEC_Success;
const BattleErrCode BattleErrCode_MAX = eBEC_Fail;
const int BattleErrCode_ARRAYSIZE = BattleErrCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* BattleErrCode_descriptor();
inline const ::std::string& BattleErrCode_Name(BattleErrCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    BattleErrCode_descriptor(), value);
}
inline bool BattleErrCode_Parse(
    const ::std::string& name, BattleErrCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BattleErrCode>(
    BattleErrCode_descriptor(), name, value);
}
// ===================================================================

class BattleUserLogin_C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserLogin_C2S) */ {
 public:
  BattleUserLogin_C2S();
  virtual ~BattleUserLogin_C2S();

  BattleUserLogin_C2S(const BattleUserLogin_C2S& from);

  inline BattleUserLogin_C2S& operator=(const BattleUserLogin_C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserLogin_C2S(BattleUserLogin_C2S&& from) noexcept
    : BattleUserLogin_C2S() {
    *this = ::std::move(from);
  }

  inline BattleUserLogin_C2S& operator=(BattleUserLogin_C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserLogin_C2S& default_instance();

  static inline const BattleUserLogin_C2S* internal_default_instance() {
    return reinterpret_cast<const BattleUserLogin_C2S*>(
               &_BattleUserLogin_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BattleUserLogin_C2S* other);
  friend void swap(BattleUserLogin_C2S& a, BattleUserLogin_C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserLogin_C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserLogin_C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserLogin_C2S& from);
  void MergeFrom(const BattleUserLogin_C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserLogin_C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // uint64 room = 2;
  void clear_room();
  static const int kRoomFieldNumber = 2;
  ::google::protobuf::uint64 room() const;
  void set_room(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserLogin_C2S)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint64 room_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserLogin_S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserLogin_S2C) */ {
 public:
  BattleUserLogin_S2C();
  virtual ~BattleUserLogin_S2C();

  BattleUserLogin_S2C(const BattleUserLogin_S2C& from);

  inline BattleUserLogin_S2C& operator=(const BattleUserLogin_S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserLogin_S2C(BattleUserLogin_S2C&& from) noexcept
    : BattleUserLogin_S2C() {
    *this = ::std::move(from);
  }

  inline BattleUserLogin_S2C& operator=(BattleUserLogin_S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserLogin_S2C& default_instance();

  static inline const BattleUserLogin_S2C* internal_default_instance() {
    return reinterpret_cast<const BattleUserLogin_S2C*>(
               &_BattleUserLogin_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(BattleUserLogin_S2C* other);
  friend void swap(BattleUserLogin_S2C& a, BattleUserLogin_S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserLogin_S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserLogin_S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserLogin_S2C& from);
  void MergeFrom(const BattleUserLogin_S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserLogin_S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .BattleMsg.BattleErrCode errcode = 1;
  void clear_errcode();
  static const int kErrcodeFieldNumber = 1;
  ::BattleMsg::BattleErrCode errcode() const;
  void set_errcode(::BattleMsg::BattleErrCode value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserLogin_S2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int errcode_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserLoadOK_C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserLoadOK_C2S) */ {
 public:
  BattleUserLoadOK_C2S();
  virtual ~BattleUserLoadOK_C2S();

  BattleUserLoadOK_C2S(const BattleUserLoadOK_C2S& from);

  inline BattleUserLoadOK_C2S& operator=(const BattleUserLoadOK_C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserLoadOK_C2S(BattleUserLoadOK_C2S&& from) noexcept
    : BattleUserLoadOK_C2S() {
    *this = ::std::move(from);
  }

  inline BattleUserLoadOK_C2S& operator=(BattleUserLoadOK_C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserLoadOK_C2S& default_instance();

  static inline const BattleUserLoadOK_C2S* internal_default_instance() {
    return reinterpret_cast<const BattleUserLoadOK_C2S*>(
               &_BattleUserLoadOK_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(BattleUserLoadOK_C2S* other);
  friend void swap(BattleUserLoadOK_C2S& a, BattleUserLoadOK_C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserLoadOK_C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserLoadOK_C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserLoadOK_C2S& from);
  void MergeFrom(const BattleUserLoadOK_C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserLoadOK_C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // uint64 room = 2;
  void clear_room();
  static const int kRoomFieldNumber = 2;
  ::google::protobuf::uint64 room() const;
  void set_room(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserLoadOK_C2S)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint64 room_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserLoadOK_S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserLoadOK_S2C) */ {
 public:
  BattleUserLoadOK_S2C();
  virtual ~BattleUserLoadOK_S2C();

  BattleUserLoadOK_S2C(const BattleUserLoadOK_S2C& from);

  inline BattleUserLoadOK_S2C& operator=(const BattleUserLoadOK_S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserLoadOK_S2C(BattleUserLoadOK_S2C&& from) noexcept
    : BattleUserLoadOK_S2C() {
    *this = ::std::move(from);
  }

  inline BattleUserLoadOK_S2C& operator=(BattleUserLoadOK_S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserLoadOK_S2C& default_instance();

  static inline const BattleUserLoadOK_S2C* internal_default_instance() {
    return reinterpret_cast<const BattleUserLoadOK_S2C*>(
               &_BattleUserLoadOK_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(BattleUserLoadOK_S2C* other);
  friend void swap(BattleUserLoadOK_S2C& a, BattleUserLoadOK_S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserLoadOK_S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserLoadOK_S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserLoadOK_S2C& from);
  void MergeFrom(const BattleUserLoadOK_S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserLoadOK_S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserLoadOK_S2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 uid_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserGameStart_S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserGameStart_S2C) */ {
 public:
  BattleUserGameStart_S2C();
  virtual ~BattleUserGameStart_S2C();

  BattleUserGameStart_S2C(const BattleUserGameStart_S2C& from);

  inline BattleUserGameStart_S2C& operator=(const BattleUserGameStart_S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserGameStart_S2C(BattleUserGameStart_S2C&& from) noexcept
    : BattleUserGameStart_S2C() {
    *this = ::std::move(from);
  }

  inline BattleUserGameStart_S2C& operator=(BattleUserGameStart_S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserGameStart_S2C& default_instance();

  static inline const BattleUserGameStart_S2C* internal_default_instance() {
    return reinterpret_cast<const BattleUserGameStart_S2C*>(
               &_BattleUserGameStart_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(BattleUserGameStart_S2C* other);
  friend void swap(BattleUserGameStart_S2C& a, BattleUserGameStart_S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserGameStart_S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserGameStart_S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserGameStart_S2C& from);
  void MergeFrom(const BattleUserGameStart_S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserGameStart_S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 time = 1;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserGameStart_S2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 time_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserOperate_C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserOperate_C2S) */ {
 public:
  BattleUserOperate_C2S();
  virtual ~BattleUserOperate_C2S();

  BattleUserOperate_C2S(const BattleUserOperate_C2S& from);

  inline BattleUserOperate_C2S& operator=(const BattleUserOperate_C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserOperate_C2S(BattleUserOperate_C2S&& from) noexcept
    : BattleUserOperate_C2S() {
    *this = ::std::move(from);
  }

  inline BattleUserOperate_C2S& operator=(BattleUserOperate_C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserOperate_C2S& default_instance();

  static inline const BattleUserOperate_C2S* internal_default_instance() {
    return reinterpret_cast<const BattleUserOperate_C2S*>(
               &_BattleUserOperate_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(BattleUserOperate_C2S* other);
  friend void swap(BattleUserOperate_C2S& a, BattleUserOperate_C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserOperate_C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserOperate_C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserOperate_C2S& from);
  void MergeFrom(const BattleUserOperate_C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserOperate_C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // uint64 room = 2;
  void clear_room();
  static const int kRoomFieldNumber = 2;
  ::google::protobuf::uint64 room() const;
  void set_room(::google::protobuf::uint64 value);

  // uint64 time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // uint32 type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // uint32 x = 5;
  void clear_x();
  static const int kXFieldNumber = 5;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // uint32 y = 6;
  void clear_y();
  static const int kYFieldNumber = 6;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // uint32 skill_id = 7;
  void clear_skill_id();
  static const int kSkillIdFieldNumber = 7;
  ::google::protobuf::uint32 skill_id() const;
  void set_skill_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserOperate_C2S)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint64 room_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  ::google::protobuf::uint32 skill_id_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleSingleFrame_S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleSingleFrame_S2C) */ {
 public:
  BattleSingleFrame_S2C();
  virtual ~BattleSingleFrame_S2C();

  BattleSingleFrame_S2C(const BattleSingleFrame_S2C& from);

  inline BattleSingleFrame_S2C& operator=(const BattleSingleFrame_S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleSingleFrame_S2C(BattleSingleFrame_S2C&& from) noexcept
    : BattleSingleFrame_S2C() {
    *this = ::std::move(from);
  }

  inline BattleSingleFrame_S2C& operator=(BattleSingleFrame_S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleSingleFrame_S2C& default_instance();

  static inline const BattleSingleFrame_S2C* internal_default_instance() {
    return reinterpret_cast<const BattleSingleFrame_S2C*>(
               &_BattleSingleFrame_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(BattleSingleFrame_S2C* other);
  friend void swap(BattleSingleFrame_S2C& a, BattleSingleFrame_S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleSingleFrame_S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleSingleFrame_S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleSingleFrame_S2C& from);
  void MergeFrom(const BattleSingleFrame_S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleSingleFrame_S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes datas = 3;
  int datas_size() const;
  void clear_datas();
  static const int kDatasFieldNumber = 3;
  const ::std::string& datas(int index) const;
  ::std::string* mutable_datas(int index);
  void set_datas(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_datas(int index, ::std::string&& value);
  #endif
  void set_datas(int index, const char* value);
  void set_datas(int index, const void* value, size_t size);
  ::std::string* add_datas();
  void add_datas(const ::std::string& value);
  #if LANG_CXX11
  void add_datas(::std::string&& value);
  #endif
  void add_datas(const char* value);
  void add_datas(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& datas() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_datas();

  // uint64 frame_index = 1;
  void clear_frame_index();
  static const int kFrameIndexFieldNumber = 1;
  ::google::protobuf::uint64 frame_index() const;
  void set_frame_index(::google::protobuf::uint64 value);

  // uint64 milli_second = 2;
  void clear_milli_second();
  static const int kMilliSecondFieldNumber = 2;
  ::google::protobuf::uint64 milli_second() const;
  void set_milli_second(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleSingleFrame_S2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> datas_;
  ::google::protobuf::uint64 frame_index_;
  ::google::protobuf::uint64 milli_second_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserLogout : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserLogout) */ {
 public:
  BattleUserLogout();
  virtual ~BattleUserLogout();

  BattleUserLogout(const BattleUserLogout& from);

  inline BattleUserLogout& operator=(const BattleUserLogout& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserLogout(BattleUserLogout&& from) noexcept
    : BattleUserLogout() {
    *this = ::std::move(from);
  }

  inline BattleUserLogout& operator=(BattleUserLogout&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserLogout& default_instance();

  static inline const BattleUserLogout* internal_default_instance() {
    return reinterpret_cast<const BattleUserLogout*>(
               &_BattleUserLogout_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(BattleUserLogout* other);
  friend void swap(BattleUserLogout& a, BattleUserLogout& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserLogout* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserLogout* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserLogout& from);
  void MergeFrom(const BattleUserLogout& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserLogout* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserLogout)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BattleUserBroadcast : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleMsg.BattleUserBroadcast) */ {
 public:
  BattleUserBroadcast();
  virtual ~BattleUserBroadcast();

  BattleUserBroadcast(const BattleUserBroadcast& from);

  inline BattleUserBroadcast& operator=(const BattleUserBroadcast& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUserBroadcast(BattleUserBroadcast&& from) noexcept
    : BattleUserBroadcast() {
    *this = ::std::move(from);
  }

  inline BattleUserBroadcast& operator=(BattleUserBroadcast&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleUserBroadcast& default_instance();

  static inline const BattleUserBroadcast* internal_default_instance() {
    return reinterpret_cast<const BattleUserBroadcast*>(
               &_BattleUserBroadcast_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(BattleUserBroadcast* other);
  friend void swap(BattleUserBroadcast& a, BattleUserBroadcast& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUserBroadcast* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUserBroadcast* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleUserBroadcast& from);
  void MergeFrom(const BattleUserBroadcast& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleUserBroadcast* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:BattleMsg.BattleUserBroadcast)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUserMsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BattleUserLogin_C2S

// uint64 uid = 1;
inline void BattleUserLogin_C2S::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserLogin_C2S::uid() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserLogin_C2S.uid)
  return uid_;
}
inline void BattleUserLogin_C2S::set_uid(::google::protobuf::uint64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserLogin_C2S.uid)
}

// uint64 room = 2;
inline void BattleUserLogin_C2S::clear_room() {
  room_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserLogin_C2S::room() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserLogin_C2S.room)
  return room_;
}
inline void BattleUserLogin_C2S::set_room(::google::protobuf::uint64 value) {
  
  room_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserLogin_C2S.room)
}

// -------------------------------------------------------------------

// BattleUserLogin_S2C

// .BattleMsg.BattleErrCode errcode = 1;
inline void BattleUserLogin_S2C::clear_errcode() {
  errcode_ = 0;
}
inline ::BattleMsg::BattleErrCode BattleUserLogin_S2C::errcode() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserLogin_S2C.errcode)
  return static_cast< ::BattleMsg::BattleErrCode >(errcode_);
}
inline void BattleUserLogin_S2C::set_errcode(::BattleMsg::BattleErrCode value) {
  
  errcode_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserLogin_S2C.errcode)
}

// -------------------------------------------------------------------

// BattleUserLoadOK_C2S

// uint64 uid = 1;
inline void BattleUserLoadOK_C2S::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserLoadOK_C2S::uid() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserLoadOK_C2S.uid)
  return uid_;
}
inline void BattleUserLoadOK_C2S::set_uid(::google::protobuf::uint64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserLoadOK_C2S.uid)
}

// uint64 room = 2;
inline void BattleUserLoadOK_C2S::clear_room() {
  room_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserLoadOK_C2S::room() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserLoadOK_C2S.room)
  return room_;
}
inline void BattleUserLoadOK_C2S::set_room(::google::protobuf::uint64 value) {
  
  room_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserLoadOK_C2S.room)
}

// -------------------------------------------------------------------

// BattleUserLoadOK_S2C

// uint64 uid = 1;
inline void BattleUserLoadOK_S2C::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserLoadOK_S2C::uid() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserLoadOK_S2C.uid)
  return uid_;
}
inline void BattleUserLoadOK_S2C::set_uid(::google::protobuf::uint64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserLoadOK_S2C.uid)
}

// -------------------------------------------------------------------

// BattleUserGameStart_S2C

// uint64 time = 1;
inline void BattleUserGameStart_S2C::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserGameStart_S2C::time() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserGameStart_S2C.time)
  return time_;
}
inline void BattleUserGameStart_S2C::set_time(::google::protobuf::uint64 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserGameStart_S2C.time)
}

// -------------------------------------------------------------------

// BattleUserOperate_C2S

// uint64 uid = 1;
inline void BattleUserOperate_C2S::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserOperate_C2S::uid() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.uid)
  return uid_;
}
inline void BattleUserOperate_C2S::set_uid(::google::protobuf::uint64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.uid)
}

// uint64 room = 2;
inline void BattleUserOperate_C2S::clear_room() {
  room_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserOperate_C2S::room() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.room)
  return room_;
}
inline void BattleUserOperate_C2S::set_room(::google::protobuf::uint64 value) {
  
  room_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.room)
}

// uint64 time = 3;
inline void BattleUserOperate_C2S::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleUserOperate_C2S::time() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.time)
  return time_;
}
inline void BattleUserOperate_C2S::set_time(::google::protobuf::uint64 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.time)
}

// uint32 type = 4;
inline void BattleUserOperate_C2S::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 BattleUserOperate_C2S::type() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.type)
  return type_;
}
inline void BattleUserOperate_C2S::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.type)
}

// uint32 x = 5;
inline void BattleUserOperate_C2S::clear_x() {
  x_ = 0u;
}
inline ::google::protobuf::uint32 BattleUserOperate_C2S::x() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.x)
  return x_;
}
inline void BattleUserOperate_C2S::set_x(::google::protobuf::uint32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.x)
}

// uint32 y = 6;
inline void BattleUserOperate_C2S::clear_y() {
  y_ = 0u;
}
inline ::google::protobuf::uint32 BattleUserOperate_C2S::y() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.y)
  return y_;
}
inline void BattleUserOperate_C2S::set_y(::google::protobuf::uint32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.y)
}

// uint32 skill_id = 7;
inline void BattleUserOperate_C2S::clear_skill_id() {
  skill_id_ = 0u;
}
inline ::google::protobuf::uint32 BattleUserOperate_C2S::skill_id() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleUserOperate_C2S.skill_id)
  return skill_id_;
}
inline void BattleUserOperate_C2S::set_skill_id(::google::protobuf::uint32 value) {
  
  skill_id_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleUserOperate_C2S.skill_id)
}

// -------------------------------------------------------------------

// BattleSingleFrame_S2C

// uint64 frame_index = 1;
inline void BattleSingleFrame_S2C::clear_frame_index() {
  frame_index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleSingleFrame_S2C::frame_index() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleSingleFrame_S2C.frame_index)
  return frame_index_;
}
inline void BattleSingleFrame_S2C::set_frame_index(::google::protobuf::uint64 value) {
  
  frame_index_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleSingleFrame_S2C.frame_index)
}

// uint64 milli_second = 2;
inline void BattleSingleFrame_S2C::clear_milli_second() {
  milli_second_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleSingleFrame_S2C::milli_second() const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleSingleFrame_S2C.milli_second)
  return milli_second_;
}
inline void BattleSingleFrame_S2C::set_milli_second(::google::protobuf::uint64 value) {
  
  milli_second_ = value;
  // @@protoc_insertion_point(field_set:BattleMsg.BattleSingleFrame_S2C.milli_second)
}

// repeated bytes datas = 3;
inline int BattleSingleFrame_S2C::datas_size() const {
  return datas_.size();
}
inline void BattleSingleFrame_S2C::clear_datas() {
  datas_.Clear();
}
inline const ::std::string& BattleSingleFrame_S2C::datas(int index) const {
  // @@protoc_insertion_point(field_get:BattleMsg.BattleSingleFrame_S2C.datas)
  return datas_.Get(index);
}
inline ::std::string* BattleSingleFrame_S2C::mutable_datas(int index) {
  // @@protoc_insertion_point(field_mutable:BattleMsg.BattleSingleFrame_S2C.datas)
  return datas_.Mutable(index);
}
inline void BattleSingleFrame_S2C::set_datas(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:BattleMsg.BattleSingleFrame_S2C.datas)
  datas_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void BattleSingleFrame_S2C::set_datas(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:BattleMsg.BattleSingleFrame_S2C.datas)
  datas_.Mutable(index)->assign(std::move(value));
}
#endif
inline void BattleSingleFrame_S2C::set_datas(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  datas_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:BattleMsg.BattleSingleFrame_S2C.datas)
}
inline void BattleSingleFrame_S2C::set_datas(int index, const void* value, size_t size) {
  datas_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BattleMsg.BattleSingleFrame_S2C.datas)
}
inline ::std::string* BattleSingleFrame_S2C::add_datas() {
  // @@protoc_insertion_point(field_add_mutable:BattleMsg.BattleSingleFrame_S2C.datas)
  return datas_.Add();
}
inline void BattleSingleFrame_S2C::add_datas(const ::std::string& value) {
  datas_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:BattleMsg.BattleSingleFrame_S2C.datas)
}
#if LANG_CXX11
inline void BattleSingleFrame_S2C::add_datas(::std::string&& value) {
  datas_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:BattleMsg.BattleSingleFrame_S2C.datas)
}
#endif
inline void BattleSingleFrame_S2C::add_datas(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  datas_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:BattleMsg.BattleSingleFrame_S2C.datas)
}
inline void BattleSingleFrame_S2C::add_datas(const void* value, size_t size) {
  datas_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:BattleMsg.BattleSingleFrame_S2C.datas)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
BattleSingleFrame_S2C::datas() const {
  // @@protoc_insertion_point(field_list:BattleMsg.BattleSingleFrame_S2C.datas)
  return datas_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
BattleSingleFrame_S2C::mutable_datas() {
  // @@protoc_insertion_point(field_mutable_list:BattleMsg.BattleSingleFrame_S2C.datas)
  return &datas_;
}

// -------------------------------------------------------------------

// BattleUserLogout

// -------------------------------------------------------------------

// BattleUserBroadcast

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace BattleMsg

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::BattleMsg::EnumBattleUserMsg> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BattleMsg::EnumBattleUserMsg>() {
  return ::BattleMsg::EnumBattleUserMsg_descriptor();
}
template <> struct is_proto_enum< ::BattleMsg::BattleErrCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BattleMsg::BattleErrCode>() {
  return ::BattleMsg::BattleErrCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleUserMsg_2eproto__INCLUDED
